config/routes.rb
Rails.application.routes.draw do

  resources :regions
  post '/rate' => 'rater#create', :as => 'rate'
  resources :profile, only: [:index, :edit]
  resources :about, :only => [:index]
# point controller for omniauth to devise
  devise_for :users, controllers: { omniauth_callbacks: "callbacks"}

  resources :houses

  resources :houses do
    resources :reviews, :bookings, except: [:show]
  end

  resources :landing, only: [:index]
  root to: 'landing#index'

# make the index of houses into /discover
end

app/models/booking.rb
# == Schema Information
#
# Table name: bookings
#
#  id         :integer          not null, primary key
#  checkin    :date
#  checkout   :date
#  occupancy  :integer
#  user_id    :integer
#  house_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :house
  validates :checkin, presence: true
  validates :checkout, presence: true
  validates :occupancy, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:new, :create, :edit, :update, :destroy]
  before_filter :must_login?, only: [:new, :edit, :destroy]
  before_action :authenticate_user!  # GET /bookings
  def index
    @bookings = Booking.all
  end

  # GET /bookings/new
  def new
    @booking = @house.bookings.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  def create
    @booking = @house.bookings.new(booking_params)
    @booking.user = current_user
    if @booking.save
      redirect_to profile_index_path, notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /bookings/1
  def update
    if @booking.update(booking_params)
      redirect_to @house, notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /bookings/1
  def destroy
    @booking.destroy
    redirect_to bookings_url, notice: 'Booking was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @house = House.find(params[:house_id])
    end

    # Only allow a trusted parameter "white list" through.
    def booking_params
      params.fetch(:booking).permit(:checkin, :checkout, :occupancy)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for [@house,@booking] do |f| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

     <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= f.label :checkin %>
    <%= f.date_select :checkin %>
  </div>

 <div class="field">
    <%= f.label :checkout %>
    <%= f.date_select :checkout %>
  </div>

 <div class="field">
    <%= f.label :occupancy %>
    <%= f.number_field :occupancy %>
  </div>

 <div class="actions">
    <%= f.submit "Book Now" %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Checkin</th>
      <th>Checkout</th>
      <th>Occupancy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.checkin %></td>
        <td><%= booking.checkout %></td>
        <td><%= booking.occupancy %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', house_path(@house) %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Checkin:</strong>
  <%= @booking.checkin %>
</p>

<p>
  <strong>Checkout:</strong>
  <%= @booking.checkout %>
</p>

<p>
  <strong>Occupancy:</strong>
  <%= @booking.occupancy %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>