config/routes.rb
Rails.application.routes.draw do

  resources :regions
  post '/rate' => 'rater#create', :as => 'rate'
  resources :profile, only: [:index, :edit]
  resources :about, :only => [:index]
# point controller for omniauth to devise
  devise_for :users, controllers: { omniauth_callbacks: "callbacks"}

  resources :houses

  resources :houses do
    resources :reviews, :bookings, except: [:show]
  end

  resources :landing, only: [:index]
  root to: 'landing#index'

# make the index of houses into /discover
end

app/views/layouts/_footer.html.erb
<!-- Start of the Footer -->
<footer class="site-footer ">
	<div class="container">
	<div class="row">
		<div class="col-md-12 address">
		<h4>Get in Touch</h4>
			<address>
				Ngong lane Plaza<br>
				1st Floor<br>
				corner room<br>
			</address>
		</div>

	</div>
	<div class="buttom-footer">
		<div class="col-md-5">@ Copyright Manyatta 2017.</div>
		<div class="col-md-7">
			<ul class="footer-nav">
				<li>
					<%= link_to "Home", landing_index_path%>
				</li>
				<li>
					<%= link_to "About"%>
				</li>
				<li>
					<a href="#">Discover</a>
				</li>


			</ul>
		</div>
	</div>

</div>

</footer>
<!-- End of the Footer-->

app/views/layouts/_how_to_use.html.erb
<div class="container-fluid how-to-use">
        <div class="row">
            <h2>Easy convinient booking</h2>

        </div>
        <div class="row icons">
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <img src="./images/search.png" alt="">
                <h3>Search</h3>
                <h5>Search for a location and see the homes available to you</h5>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <img src="./images/book.png" alt="">
                <h3>Book</h3>
                <h5>With our one click booking system booking homes is easier</h5>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <img src="./images/travel.png" alt="">
                <h3>Travel</h3>
                <h5>Don't worry about the boring stuff we got you just go forth</h5>
            </div>

        </div>

    </div>

app/views/layouts/_jumbotron.html.erb
<div class="jumbotron">
        <div class="container-fluid header-lg-text">
            <!-- header large text -->
            <div class="row">
                <h1>The Ultimate African Home Safari</h1>
            </div>

            <!-- header large text -->
            <!--  input gro<div class="col-md-2"></div>up-->
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-2"></div>

                <div class="col-xs-12 col-sm-12 col-md-8">

                    <div class="input-group input-group-lg">

                        <input type="text" placeholder="Where do you go next?" class="form-control">

                        <span class="input-group-btn">

          <button type="button" name="button" class="btn btn-default btn-lg">Search</button>

        </span>

                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-2"></div>

            </div>
            <!--  input group-->
        </div>

    </div>

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand header" href="#">MANYATTA</a> -->
      <%=link_to "MANYATTA", landing_index_path, class: "navbar-brand heads"%>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <!-- Discover  -->
        <li>
          <%=link_to "Discover", houses_path%>
        </li>
        <% if user_signed_in? %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= image_tag current_user.avatar.url(:thumb)%>         
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <!-- user profile -->
            <li>
              <%=link_to "profile", profile_index_path%>
            </li>
            <!-- create a house-->
            <li>
              <%=link_to "Add House",  new_house_path%>
            </li>
            <!-- create region -->
            <% if current_user.admin? %>
              <li>
                <%=link_to "create Region", new_region_path%>
              </li>
            <% end %>
            <!-- sign out -->
            <li>
              <%=link_to "sign out", destroy_user_session_path, method: :delete%>
            </li>
          </ul>
        </li>
      <% else %>
        <!-- signUp -->
        <li>
          <%=link_to "sign up", new_user_registration_path%>
        </li>
        <!-- SignIn -->
        <li>
          <%= link_to "Sign In", new_user_session_path%>
        </li>
        <% end %>
        <!-- plantrip -->
        <li>
          <button class="btn btn-primary btn-lg">Plan Trip</button>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Manyatta</title>
        <%= csrf_meta_tags %>

      <link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet">
        <script src="https://use.fontawesome.com/5e20327b09.js"></script>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <script async defer
          src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLEMAP_API_KEY']%>&callback=initMap">
        </script>
    </head>

    <body>
        <div class="row">
          <div class="container-fluid">
            <%= render("/layouts/navbar")%>
          </div>
        </div>
        <div class="row" >
          <div class="container-fluid">

          <div id="content">

          <% if notice %>
          <div id="notice_wrapper">
            <p class="notice"><%= notice %></p>
          </div>
          <% elsif alert%>
            <div id="notice_wrapper">
              <p class="alert"><%= alert %></p>
            </div>
          <% end %>
              <%= yield %>
            </div>       
          </div>
          </div>
        </div>
        <div class="row">
          <%= render("/layouts/footer")%>
        </div>
    </body>
</html>